name: limon
channels:
  - conda-forge
dependencies:
  - cmake=4.0.1
  - docopt
  - Eigen=3.4.*
  - hatchling=1.27.0
  - matplotlib=3.9.2
  - numpy=2.0.*
  - pip
  - poetry=2.1.3
  - pybind11=2.13.6
  - python=3.12.*
  - pyyaml=6.0.2
  - scikit-build-core>=0.11